use_default_settings: true
server:
  secret_key: "overridden-by-SEARXNG_SECRET"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  public_instance: false
search:
  formats:
    - html
    - json
